/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SendXAppServerV2) {
      root.SendXAppServerV2 = {};
    }
    root.SendXAppServerV2.ModelsDripStepRequest = factory(root.SendXAppServerV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ModelsDripStepRequest model module.
   * @module model/ModelsDripStepRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsDripStepRequest</code>.
   * @alias module:model/ModelsDripStepRequest
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsDripStepRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsDripStepRequest} obj Optional instance to populate.
   * @return {module:model/ModelsDripStepRequest} The populated <code>ModelsDripStepRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('autogeneratePlainText'))
        obj.autogeneratePlainText = ApiClient.convertToType(data['autogeneratePlainText'], 'Boolean');
      if (data.hasOwnProperty('duration'))
        obj.duration = ApiClient.convertToType(data['duration'], 'Number');
      if (data.hasOwnProperty('durationUnit'))
        obj.durationUnit = ApiClient.convertToType(data['durationUnit'], 'Number');
      if (data.hasOwnProperty('fromEmail'))
        obj.fromEmail = ApiClient.convertToType(data['fromEmail'], 'String');
      if (data.hasOwnProperty('fromName'))
        obj.fromName = ApiClient.convertToType(data['fromName'], 'String');
      if (data.hasOwnProperty('htmlCode'))
        obj.htmlCode = ApiClient.convertToType(data['htmlCode'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('plainText'))
        obj.plainText = ApiClient.convertToType(data['plainText'], 'String');
      if (data.hasOwnProperty('segmentstr'))
        obj.segmentstr = ApiClient.convertToType(data['segmentstr'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'Number');
      if (data.hasOwnProperty('subject'))
        obj.subject = ApiClient.convertToType(data['subject'], 'String');
      if (data.hasOwnProperty('templateCode'))
        obj.templateCode = ApiClient.convertToType(data['templateCode'], 'String');
    }
    return obj;
  }

  /**
   * @member {Boolean} autogeneratePlainText
   */
  exports.prototype.autogeneratePlainText = undefined;

  /**
   * @member {Number} duration
   */
  exports.prototype.duration = undefined;

  /**
   * @member {Number} durationUnit
   */
  exports.prototype.durationUnit = undefined;

  /**
   * @member {String} fromEmail
   */
  exports.prototype.fromEmail = undefined;

  /**
   * @member {String} fromName
   */
  exports.prototype.fromName = undefined;

  /**
   * @member {String} htmlCode
   */
  exports.prototype.htmlCode = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} plainText
   */
  exports.prototype.plainText = undefined;

  /**
   * @member {String} segmentstr
   */
  exports.prototype.segmentstr = undefined;

  /**
   * @member {Number} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {String} subject
   */
  exports.prototype.subject = undefined;

  /**
   * @member {String} templateCode
   */
  exports.prototype.templateCode = undefined;


  return exports;

}));
