/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsBulkActionType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsBulkActionType'));
  } else {
    // Browser globals (root is window)
    if (!root.SendXAppServerV2) {
      root.SendXAppServerV2 = {};
    }
    root.SendXAppServerV2.ModelsBulkAction = factory(root.SendXAppServerV2.ApiClient, root.SendXAppServerV2.ModelsBulkActionType);
  }
}(this, function(ApiClient, ModelsBulkActionType) {
  'use strict';

  /**
   * The ModelsBulkAction model module.
   * @module model/ModelsBulkAction
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsBulkAction</code>.
   * @alias module:model/ModelsBulkAction
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsBulkAction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsBulkAction} obj Optional instance to populate.
   * @return {module:model/ModelsBulkAction} The populated <code>ModelsBulkAction</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('metadata'))
        obj.metadata = ApiClient.convertToType(data['metadata'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ModelsBulkActionType.constructFromObject(data['type']);
    }
    return obj;
  }

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} metadata
   */
  exports.prototype.metadata = undefined;

  /**
   * @member {module:model/ModelsBulkActionType} type
   */
  exports.prototype.type = undefined;


  return exports;

}));
