/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SendXAppServerV2) {
      root.SendXAppServerV2 = {};
    }
    root.SendXAppServerV2.ModelsMember = factory(root.SendXAppServerV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ModelsMember model module.
   * @module model/ModelsMember
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsMember</code>.
   * @alias module:model/ModelsMember
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsMember</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsMember} obj Optional instance to populate.
   * @return {module:model/ModelsMember} The populated <code>ModelsMember</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('AvatarUrl'))
        obj.avatarUrl = ApiClient.convertToType(data['AvatarUrl'], 'String');
      if (data.hasOwnProperty('Created'))
        obj.created = ApiClient.convertToType(data['Created'], 'String');
      if (data.hasOwnProperty('Email'))
        obj.email = ApiClient.convertToType(data['Email'], 'String');
      if (data.hasOwnProperty('Id'))
        obj.id = ApiClient.convertToType(data['Id'], 'Number');
      if (data.hasOwnProperty('IsVerified'))
        obj.isVerified = ApiClient.convertToType(data['IsVerified'], 'Boolean');
      if (data.hasOwnProperty('Lang'))
        obj.lang = ApiClient.convertToType(data['Lang'], 'Number');
      if (data.hasOwnProperty('Password'))
        obj.password = ApiClient.convertToType(data['Password'], 'String');
      if (data.hasOwnProperty('Rands'))
        obj.rands = ApiClient.convertToType(data['Rands'], 'String');
      if (data.hasOwnProperty('Timezone'))
        obj.timezone = ApiClient.convertToType(data['Timezone'], 'String');
      if (data.hasOwnProperty('UserName'))
        obj.userName = ApiClient.convertToType(data['UserName'], 'String');
      if (data.hasOwnProperty('encrypted_id'))
        obj.encryptedId = ApiClient.convertToType(data['encrypted_id'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} avatarUrl
   */
  exports.prototype.avatarUrl = undefined;

  /**
   * @member {String} created
   */
  exports.prototype.created = undefined;

  /**
   * @member {String} email
   */
  exports.prototype.email = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {Boolean} isVerified
   */
  exports.prototype.isVerified = undefined;

  /**
   * @member {Number} lang
   */
  exports.prototype.lang = undefined;

  /**
   * @member {String} password
   */
  exports.prototype.password = undefined;

  /**
   * @member {String} rands
   */
  exports.prototype.rands = undefined;

  /**
   * @member {String} timezone
   */
  exports.prototype.timezone = undefined;

  /**
   * @member {String} userName
   */
  exports.prototype.userName = undefined;

  /**
   * @member {String} encryptedId
   */
  exports.prototype.encryptedId = undefined;


  return exports;

}));
