/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsBulkActionRequest', 'model/ModelsBulkTriggerRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsBulkActionRequest'), require('./ModelsBulkTriggerRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.SendXAppServerV2) {
      root.SendXAppServerV2 = {};
    }
    root.SendXAppServerV2.ModelsBulkRequest = factory(root.SendXAppServerV2.ApiClient, root.SendXAppServerV2.ModelsBulkActionRequest, root.SendXAppServerV2.ModelsBulkTriggerRequest);
  }
}(this, function(ApiClient, ModelsBulkActionRequest, ModelsBulkTriggerRequest) {
  'use strict';

  /**
   * The ModelsBulkRequest model module.
   * @module model/ModelsBulkRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsBulkRequest</code>.
   * @alias module:model/ModelsBulkRequest
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsBulkRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsBulkRequest} obj Optional instance to populate.
   * @return {module:model/ModelsBulkRequest} The populated <code>ModelsBulkRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('bulkAction'))
        obj.bulkAction = ApiClient.convertToType(data['bulkAction'], [ModelsBulkActionRequest]);
      if (data.hasOwnProperty('bulkTrigger'))
        obj.bulkTrigger = ApiClient.convertToType(data['bulkTrigger'], [ModelsBulkTriggerRequest]);
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ModelsBulkActionRequest>} bulkAction
   */
  exports.prototype.bulkAction = undefined;

  /**
   * @member {Array.<module:model/ModelsBulkTriggerRequest>} bulkTrigger
   */
  exports.prototype.bulkTrigger = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;


  return exports;

}));
