/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsTeam'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsTeam'));
  } else {
    // Browser globals (root is window)
    if (!root.SendXAppServerV2) {
      root.SendXAppServerV2 = {};
    }
    root.SendXAppServerV2.ModelsFile = factory(root.SendXAppServerV2.ApiClient, root.SendXAppServerV2.ModelsTeam);
  }
}(this, function(ApiClient, ModelsTeam) {
  'use strict';

  /**
   * The ModelsFile model module.
   * @module model/ModelsFile
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsFile</code>.
   * @alias module:model/ModelsFile
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsFile</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsFile} obj Optional instance to populate.
   * @return {module:model/ModelsFile} The populated <code>ModelsFile</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Created'))
        obj.created = ApiClient.convertToType(data['Created'], 'String');
      if (data.hasOwnProperty('Ext'))
        obj.ext = ApiClient.convertToType(data['Ext'], 'Number');
      if (data.hasOwnProperty('Id'))
        obj.id = ApiClient.convertToType(data['Id'], 'Number');
      if (data.hasOwnProperty('Name'))
        obj.name = ApiClient.convertToType(data['Name'], 'String');
      if (data.hasOwnProperty('Team'))
        obj.team = ModelsTeam.constructFromObject(data['Team']);
    }
    return obj;
  }

  /**
   * @member {String} created
   */
  exports.prototype.created = undefined;

  /**
   * @member {Number} ext
   */
  exports.prototype.ext = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {module:model/ModelsTeam} team
   */
  exports.prototype.team = undefined;


  return exports;

}));
