/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsDripStepRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsDripStepRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.SendXAppServerV2) {
      root.SendXAppServerV2 = {};
    }
    root.SendXAppServerV2.ModelsDripRequest = factory(root.SendXAppServerV2.ApiClient, root.SendXAppServerV2.ModelsDripStepRequest);
  }
}(this, function(ApiClient, ModelsDripStepRequest) {
  'use strict';

  /**
   * The ModelsDripRequest model module.
   * @module model/ModelsDripRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsDripRequest</code>.
   * @alias module:model/ModelsDripRequest
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsDripRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsDripRequest} obj Optional instance to populate.
   * @return {module:model/ModelsDripRequest} The populated <code>ModelsDripRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('autogenerateUtm'))
        obj.autogenerateUtm = ApiClient.convertToType(data['autogenerateUtm'], 'Boolean');
      if (data.hasOwnProperty('dripStep'))
        obj.dripStep = ApiClient.convertToType(data['dripStep'], [ModelsDripStepRequest]);
      if (data.hasOwnProperty('dripSteps'))
        obj.dripSteps = ApiClient.convertToType(data['dripSteps'], 'String');
      if (data.hasOwnProperty('fromEmail'))
        obj.fromEmail = ApiClient.convertToType(data['fromEmail'], 'String');
      if (data.hasOwnProperty('fromName'))
        obj.fromName = ApiClient.convertToType(data['fromName'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('sendInContactsTimezone'))
        obj.sendInContactsTimezone = ApiClient.convertToType(data['sendInContactsTimezone'], 'Boolean');
      if (data.hasOwnProperty('skipWeekends'))
        obj.skipWeekends = ApiClient.convertToType(data['skipWeekends'], 'Boolean');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'Boolean');
      if (data.hasOwnProperty('timeCondition'))
        obj.timeCondition = ApiClient.convertToType(data['timeCondition'], 'String');
      if (data.hasOwnProperty('timezone'))
        obj.timezone = ApiClient.convertToType(data['timezone'], 'String');
      if (data.hasOwnProperty('trackReply'))
        obj.trackReply = ApiClient.convertToType(data['trackReply'], 'Boolean');
    }
    return obj;
  }

  /**
   * @member {Boolean} autogenerateUtm
   */
  exports.prototype.autogenerateUtm = undefined;

  /**
   * @member {Array.<module:model/ModelsDripStepRequest>} dripStep
   */
  exports.prototype.dripStep = undefined;

  /**
   * @member {String} dripSteps
   */
  exports.prototype.dripSteps = undefined;

  /**
   * @member {String} fromEmail
   */
  exports.prototype.fromEmail = undefined;

  /**
   * @member {String} fromName
   */
  exports.prototype.fromName = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {Boolean} sendInContactsTimezone
   */
  exports.prototype.sendInContactsTimezone = undefined;

  /**
   * @member {Boolean} skipWeekends
   */
  exports.prototype.skipWeekends = undefined;

  /**
   * @member {Boolean} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {String} timeCondition
   */
  exports.prototype.timeCondition = undefined;

  /**
   * @member {String} timezone
   */
  exports.prototype.timezone = undefined;

  /**
   * @member {Boolean} trackReply
   */
  exports.prototype.trackReply = undefined;


  return exports;

}));
