/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsContactSource', 'model/ModelsContactType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsContactSource'), require('./ModelsContactType'));
  } else {
    // Browser globals (root is window)
    if (!root.SendXAppServerV2) {
      root.SendXAppServerV2 = {};
    }
    root.SendXAppServerV2.ModelsContact = factory(root.SendXAppServerV2.ApiClient, root.SendXAppServerV2.ModelsContactSource, root.SendXAppServerV2.ModelsContactType);
  }
}(this, function(ApiClient, ModelsContactSource, ModelsContactType) {
  'use strict';

  /**
   * The ModelsContact model module.
   * @module model/ModelsContact
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsContact</code>.
   * @alias module:model/ModelsContact
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsContact</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsContact} obj Optional instance to populate.
   * @return {module:model/ModelsContact} The populated <code>ModelsContact</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('ContactSource'))
        obj.contactSource = ModelsContactSource.constructFromObject(data['ContactSource']);
      if (data.hasOwnProperty('Created'))
        obj.created = ApiClient.convertToType(data['Created'], 'String');
      if (data.hasOwnProperty('LTV'))
        obj.LTV = ApiClient.convertToType(data['LTV'], 'Number');
      if (data.hasOwnProperty('Type'))
        obj.type = ModelsContactType.constructFromObject(data['Type']);
      if (data.hasOwnProperty('Updated'))
        obj.updated = ApiClient.convertToType(data['Updated'], 'String');
      if (data.hasOwnProperty('birthday'))
        obj.birthday = ApiClient.convertToType(data['birthday'], 'String');
      if (data.hasOwnProperty('blocked'))
        obj.blocked = ApiClient.convertToType(data['blocked'], 'Boolean');
      if (data.hasOwnProperty('bounced'))
        obj.bounced = ApiClient.convertToType(data['bounced'], 'Boolean');
      if (data.hasOwnProperty('company'))
        obj.company = ApiClient.convertToType(data['company'], 'String');
      if (data.hasOwnProperty('contactSourceId'))
        obj.contactSourceId = ApiClient.convertToType(data['contactSourceId'], 'Number');
      if (data.hasOwnProperty('custom_fields'))
        obj.customFields = ApiClient.convertToType(data['custom_fields'], 'String');
      if (data.hasOwnProperty('dropped'))
        obj.dropped = ApiClient.convertToType(data['dropped'], 'Boolean');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('encryptedId'))
        obj.encryptedId = ApiClient.convertToType(data['encryptedId'], 'String');
      if (data.hasOwnProperty('first_name'))
        obj.firstName = ApiClient.convertToType(data['first_name'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('last_name'))
        obj.lastName = ApiClient.convertToType(data['last_name'], 'String');
      if (data.hasOwnProperty('page_source'))
        obj.pageSource = ApiClient.convertToType(data['page_source'], 'String');
      if (data.hasOwnProperty('spam'))
        obj.spam = ApiClient.convertToType(data['spam'], 'Boolean');
      if (data.hasOwnProperty('track_data'))
        obj.trackData = ApiClient.convertToType(data['track_data'], 'String');
      if (data.hasOwnProperty('unsubscribed'))
        obj.unsubscribed = ApiClient.convertToType(data['unsubscribed'], 'Boolean');
    }
    return obj;
  }

  /**
   * @member {module:model/ModelsContactSource} contactSource
   */
  exports.prototype.contactSource = undefined;

  /**
   * @member {String} created
   */
  exports.prototype.created = undefined;

  /**
   * @member {Number} LTV
   */
  exports.prototype.LTV = undefined;

  /**
   * @member {module:model/ModelsContactType} type
   */
  exports.prototype.type = undefined;

  /**
   * @member {String} updated
   */
  exports.prototype.updated = undefined;

  /**
   * @member {String} birthday
   */
  exports.prototype.birthday = undefined;

  /**
   * @member {Boolean} blocked
   */
  exports.prototype.blocked = undefined;

  /**
   * @member {Boolean} bounced
   */
  exports.prototype.bounced = undefined;

  /**
   * @member {String} company
   */
  exports.prototype.company = undefined;

  /**
   * @member {Number} contactSourceId
   */
  exports.prototype.contactSourceId = undefined;

  /**
   * @member {String} customFields
   */
  exports.prototype.customFields = undefined;

  /**
   * @member {Boolean} dropped
   */
  exports.prototype.dropped = undefined;

  /**
   * @member {String} email
   */
  exports.prototype.email = undefined;

  /**
   * @member {String} encryptedId
   */
  exports.prototype.encryptedId = undefined;

  /**
   * @member {String} firstName
   */
  exports.prototype.firstName = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} lastName
   */
  exports.prototype.lastName = undefined;

  /**
   * @member {String} pageSource
   */
  exports.prototype.pageSource = undefined;

  /**
   * @member {Boolean} spam
   */
  exports.prototype.spam = undefined;

  /**
   * @member {String} trackData
   */
  exports.prototype.trackData = undefined;

  /**
   * @member {Boolean} unsubscribed
   */
  exports.prototype.unsubscribed = undefined;


  return exports;

}));
