/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsCampaignStatus', 'model/ModelsCampaignType', 'model/ModelsChannel', 'model/ModelsScheduleType', 'model/ModelsSelect2ElementWrapper'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsCampaignStatus'), require('./ModelsCampaignType'), require('./ModelsChannel'), require('./ModelsScheduleType'), require('./ModelsSelect2ElementWrapper'));
  } else {
    // Browser globals (root is window)
    if (!root.SendXAppServerV2) {
      root.SendXAppServerV2 = {};
    }
    root.SendXAppServerV2.ModelsCampaign = factory(root.SendXAppServerV2.ApiClient, root.SendXAppServerV2.ModelsCampaignStatus, root.SendXAppServerV2.ModelsCampaignType, root.SendXAppServerV2.ModelsChannel, root.SendXAppServerV2.ModelsScheduleType, root.SendXAppServerV2.ModelsSelect2ElementWrapper);
  }
}(this, function(ApiClient, ModelsCampaignStatus, ModelsCampaignType, ModelsChannel, ModelsScheduleType, ModelsSelect2ElementWrapper) {
  'use strict';

  /**
   * The ModelsCampaign model module.
   * @module model/ModelsCampaign
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsCampaign</code>.
   * @alias module:model/ModelsCampaign
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsCampaign</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsCampaign} obj Optional instance to populate.
   * @return {module:model/ModelsCampaign} The populated <code>ModelsCampaign</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('aBTestCampaign'))
        obj.aBTestCampaign = ApiClient.convertToType(data['aBTestCampaign'], 'Boolean');
      if (data.hasOwnProperty('autodraftMetadata'))
        obj.autodraftMetadata = ApiClient.convertToType(data['autodraftMetadata'], 'String');
      if (data.hasOwnProperty('autogeneratePlainText'))
        obj.autogeneratePlainText = ApiClient.convertToType(data['autogeneratePlainText'], 'Boolean');
      if (data.hasOwnProperty('autogenerateUTM'))
        obj.autogenerateUTM = ApiClient.convertToType(data['autogenerateUTM'], 'Boolean');
      if (data.hasOwnProperty('channel'))
        obj.channel = ModelsChannel.constructFromObject(data['channel']);
      if (data.hasOwnProperty('encryptedId'))
        obj.encryptedId = ApiClient.convertToType(data['encryptedId'], 'String');
      if (data.hasOwnProperty('excludedSegmentOptions'))
        obj.excludedSegmentOptions = ApiClient.convertToType(data['excludedSegmentOptions'], [ModelsSelect2ElementWrapper]);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('includedSegmentOptions'))
        obj.includedSegmentOptions = ApiClient.convertToType(data['includedSegmentOptions'], [ModelsSelect2ElementWrapper]);
      if (data.hasOwnProperty('metadata'))
        obj.metadata = ApiClient.convertToType(data['metadata'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('preferredTimeCondition'))
        obj.preferredTimeCondition = ApiClient.convertToType(data['preferredTimeCondition'], 'String');
      if (data.hasOwnProperty('preferredTimezone'))
        obj.preferredTimezone = ApiClient.convertToType(data['preferredTimezone'], 'String');
      if (data.hasOwnProperty('scheduleCondition'))
        obj.scheduleCondition = ApiClient.convertToType(data['scheduleCondition'], 'String');
      if (data.hasOwnProperty('scheduleType'))
        obj.scheduleType = ModelsScheduleType.constructFromObject(data['scheduleType']);
      if (data.hasOwnProperty('sendInContactsTimezone'))
        obj.sendInContactsTimezone = ApiClient.convertToType(data['sendInContactsTimezone'], 'Boolean');
      if (data.hasOwnProperty('smartSend'))
        obj.smartSend = ApiClient.convertToType(data['smartSend'], 'Boolean');
      if (data.hasOwnProperty('status'))
        obj.status = ModelsCampaignStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('strategy'))
        obj.strategy = ApiClient.convertToType(data['strategy'], 'String');
      if (data.hasOwnProperty('timeCondition'))
        obj.timeCondition = ApiClient.convertToType(data['timeCondition'], 'String');
      if (data.hasOwnProperty('timezone'))
        obj.timezone = ApiClient.convertToType(data['timezone'], 'String');
      if (data.hasOwnProperty('trackReply'))
        obj.trackReply = ApiClient.convertToType(data['trackReply'], 'Boolean');
      if (data.hasOwnProperty('type'))
        obj.type = ModelsCampaignType.constructFromObject(data['type']);
    }
    return obj;
  }

  /**
   * @member {Boolean} aBTestCampaign
   */
  exports.prototype.aBTestCampaign = undefined;

  /**
   * @member {String} autodraftMetadata
   */
  exports.prototype.autodraftMetadata = undefined;

  /**
   * @member {Boolean} autogeneratePlainText
   */
  exports.prototype.autogeneratePlainText = undefined;

  /**
   * @member {Boolean} autogenerateUTM
   */
  exports.prototype.autogenerateUTM = undefined;

  /**
   * @member {module:model/ModelsChannel} channel
   */
  exports.prototype.channel = undefined;

  /**
   * @member {String} encryptedId
   */
  exports.prototype.encryptedId = undefined;

  /**
   * @member {Array.<module:model/ModelsSelect2ElementWrapper>} excludedSegmentOptions
   */
  exports.prototype.excludedSegmentOptions = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {Array.<module:model/ModelsSelect2ElementWrapper>} includedSegmentOptions
   */
  exports.prototype.includedSegmentOptions = undefined;

  /**
   * @member {String} metadata
   */
  exports.prototype.metadata = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} preferredTimeCondition
   */
  exports.prototype.preferredTimeCondition = undefined;

  /**
   * @member {String} preferredTimezone
   */
  exports.prototype.preferredTimezone = undefined;

  /**
   * @member {String} scheduleCondition
   */
  exports.prototype.scheduleCondition = undefined;

  /**
   * @member {module:model/ModelsScheduleType} scheduleType
   */
  exports.prototype.scheduleType = undefined;

  /**
   * @member {Boolean} sendInContactsTimezone
   */
  exports.prototype.sendInContactsTimezone = undefined;

  /**
   * @member {Boolean} smartSend
   */
  exports.prototype.smartSend = undefined;

  /**
   * @member {module:model/ModelsCampaignStatus} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {String} strategy
   */
  exports.prototype.strategy = undefined;

  /**
   * @member {String} timeCondition
   */
  exports.prototype.timeCondition = undefined;

  /**
   * @member {String} timezone
   */
  exports.prototype.timezone = undefined;

  /**
   * @member {Boolean} trackReply
   */
  exports.prototype.trackReply = undefined;

  /**
   * @member {module:model/ModelsCampaignType} type
   */
  exports.prototype.type = undefined;


  return exports;

}));
