/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsListType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsListType'));
  } else {
    // Browser globals (root is window)
    if (!root.SendXAppServerV2) {
      root.SendXAppServerV2 = {};
    }
    root.SendXAppServerV2.ModelsList = factory(root.SendXAppServerV2.ApiClient, root.SendXAppServerV2.ModelsListType);
  }
}(this, function(ApiClient, ModelsListType) {
  'use strict';

  /**
   * The ModelsList model module.
   * @module model/ModelsList
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsList</code>.
   * @alias module:model/ModelsList
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsList} obj Optional instance to populate.
   * @return {module:model/ModelsList} The populated <code>ModelsList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('confirmFromEmail'))
        obj.confirmFromEmail = ApiClient.convertToType(data['confirmFromEmail'], 'String');
      if (data.hasOwnProperty('confirmFromName'))
        obj.confirmFromName = ApiClient.convertToType(data['confirmFromName'], 'String');
      if (data.hasOwnProperty('confirmMailMessage'))
        obj.confirmMailMessage = ApiClient.convertToType(data['confirmMailMessage'], 'String');
      if (data.hasOwnProperty('confirmMailSubject'))
        obj.confirmMailSubject = ApiClient.convertToType(data['confirmMailSubject'], 'String');
      if (data.hasOwnProperty('confirmSuccessPage'))
        obj.confirmSuccessPage = ApiClient.convertToType(data['confirmSuccessPage'], 'String');
      if (data.hasOwnProperty('encrypted'))
        obj.encrypted = ApiClient.convertToType(data['encrypted'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('sendThankYouMail'))
        obj.sendThankYouMail = ApiClient.convertToType(data['sendThankYouMail'], 'Boolean');
      if (data.hasOwnProperty('thankYouFromEmail'))
        obj.thankYouFromEmail = ApiClient.convertToType(data['thankYouFromEmail'], 'String');
      if (data.hasOwnProperty('thankYouFromName'))
        obj.thankYouFromName = ApiClient.convertToType(data['thankYouFromName'], 'String');
      if (data.hasOwnProperty('thankYouMailMessage'))
        obj.thankYouMailMessage = ApiClient.convertToType(data['thankYouMailMessage'], 'String');
      if (data.hasOwnProperty('thankYouMailSubject'))
        obj.thankYouMailSubject = ApiClient.convertToType(data['thankYouMailSubject'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ModelsListType.constructFromObject(data['type']);
    }
    return obj;
  }

  /**
   * @member {String} confirmFromEmail
   */
  exports.prototype.confirmFromEmail = undefined;

  /**
   * @member {String} confirmFromName
   */
  exports.prototype.confirmFromName = undefined;

  /**
   * @member {String} confirmMailMessage
   */
  exports.prototype.confirmMailMessage = undefined;

  /**
   * @member {String} confirmMailSubject
   */
  exports.prototype.confirmMailSubject = undefined;

  /**
   * @member {String} confirmSuccessPage
   */
  exports.prototype.confirmSuccessPage = undefined;

  /**
   * @member {String} encrypted
   */
  exports.prototype.encrypted = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {Boolean} sendThankYouMail
   */
  exports.prototype.sendThankYouMail = undefined;

  /**
   * @member {String} thankYouFromEmail
   */
  exports.prototype.thankYouFromEmail = undefined;

  /**
   * @member {String} thankYouFromName
   */
  exports.prototype.thankYouFromName = undefined;

  /**
   * @member {String} thankYouMailMessage
   */
  exports.prototype.thankYouMailMessage = undefined;

  /**
   * @member {String} thankYouMailSubject
   */
  exports.prototype.thankYouMailSubject = undefined;

  /**
   * @member {module:model/ModelsListType} type
   */
  exports.prototype.type = undefined;


  return exports;

}));
