/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsAutomationAction', 'model/ModelsAutomationTrigger'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsAutomationAction'), require('./ModelsAutomationTrigger'));
  } else {
    // Browser globals (root is window)
    if (!root.SendXAppServerV2) {
      root.SendXAppServerV2 = {};
    }
    root.SendXAppServerV2.ModelsDeepTeamAutomation = factory(root.SendXAppServerV2.ApiClient, root.SendXAppServerV2.ModelsAutomationAction, root.SendXAppServerV2.ModelsAutomationTrigger);
  }
}(this, function(ApiClient, ModelsAutomationAction, ModelsAutomationTrigger) {
  'use strict';

  /**
   * The ModelsDeepTeamAutomation model module.
   * @module model/ModelsDeepTeamAutomation
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsDeepTeamAutomation</code>.
   * @alias module:model/ModelsDeepTeamAutomation
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsDeepTeamAutomation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsDeepTeamAutomation} obj Optional instance to populate.
   * @return {module:model/ModelsDeepTeamAutomation} The populated <code>ModelsDeepTeamAutomation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('actions'))
        obj.actions = ApiClient.convertToType(data['actions'], [ModelsAutomationAction]);
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'Boolean');
      if (data.hasOwnProperty('triggers'))
        obj.triggers = ApiClient.convertToType(data['triggers'], [ModelsAutomationTrigger]);
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ModelsAutomationAction>} actions
   */
  exports.prototype.actions = undefined;

  /**
   * @member {String} _date
   */
  exports.prototype._date = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {Boolean} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {Array.<module:model/ModelsAutomationTrigger>} triggers
   */
  exports.prototype.triggers = undefined;


  return exports;

}));
