/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SendXAppServerV2) {
      root.SendXAppServerV2 = {};
    }
    root.SendXAppServerV2.ModelsCampaignRequest = factory(root.SendXAppServerV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ModelsCampaignRequest model module.
   * @module model/ModelsCampaignRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsCampaignRequest</code>.
   * @alias module:model/ModelsCampaignRequest
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsCampaignRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsCampaignRequest} obj Optional instance to populate.
   * @return {module:model/ModelsCampaignRequest} The populated <code>ModelsCampaignRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('attachmentIdStr'))
        obj.attachmentIdStr = ApiClient.convertToType(data['attachmentIdStr'], 'String');
      if (data.hasOwnProperty('autogeneratePlainText'))
        obj.autogeneratePlainText = ApiClient.convertToType(data['autogeneratePlainText'], 'Boolean');
      if (data.hasOwnProperty('autogenerateUTM'))
        obj.autogenerateUTM = ApiClient.convertToType(data['autogenerateUTM'], 'Boolean');
      if (data.hasOwnProperty('excludedSegmentStr'))
        obj.excludedSegmentStr = ApiClient.convertToType(data['excludedSegmentStr'], 'String');
      if (data.hasOwnProperty('fromEmail'))
        obj.fromEmail = ApiClient.convertToType(data['fromEmail'], 'String');
      if (data.hasOwnProperty('fromName'))
        obj.fromName = ApiClient.convertToType(data['fromName'], 'String');
      if (data.hasOwnProperty('htmlCode'))
        obj.htmlCode = ApiClient.convertToType(data['htmlCode'], 'String');
      if (data.hasOwnProperty('includedSegmentStr'))
        obj.includedSegmentStr = ApiClient.convertToType(data['includedSegmentStr'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('plainText'))
        obj.plainText = ApiClient.convertToType(data['plainText'], 'String');
      if (data.hasOwnProperty('preferredTimeCondition'))
        obj.preferredTimeCondition = ApiClient.convertToType(data['preferredTimeCondition'], 'String');
      if (data.hasOwnProperty('preferredTimezone'))
        obj.preferredTimezone = ApiClient.convertToType(data['preferredTimezone'], 'String');
      if (data.hasOwnProperty('rss'))
        obj.rss = ApiClient.convertToType(data['rss'], 'String');
      if (data.hasOwnProperty('scheduleCondition'))
        obj.scheduleCondition = ApiClient.convertToType(data['scheduleCondition'], 'String');
      if (data.hasOwnProperty('scheduleType'))
        obj.scheduleType = ApiClient.convertToType(data['scheduleType'], 'Number');
      if (data.hasOwnProperty('sendInContactsTimezone'))
        obj.sendInContactsTimezone = ApiClient.convertToType(data['sendInContactsTimezone'], 'Boolean');
      if (data.hasOwnProperty('smartSend'))
        obj.smartSend = ApiClient.convertToType(data['smartSend'], 'Boolean');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'Number');
      if (data.hasOwnProperty('subject'))
        obj.subject = ApiClient.convertToType(data['subject'], 'String');
      if (data.hasOwnProperty('templateCode'))
        obj.templateCode = ApiClient.convertToType(data['templateCode'], 'String');
      if (data.hasOwnProperty('timeCondition'))
        obj.timeCondition = ApiClient.convertToType(data['timeCondition'], 'String');
      if (data.hasOwnProperty('timezone'))
        obj.timezone = ApiClient.convertToType(data['timezone'], 'String');
      if (data.hasOwnProperty('trackReply'))
        obj.trackReply = ApiClient.convertToType(data['trackReply'], 'Boolean');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'Number');
    }
    return obj;
  }

  /**
   * @member {String} attachmentIdStr
   */
  exports.prototype.attachmentIdStr = undefined;

  /**
   * @member {Boolean} autogeneratePlainText
   */
  exports.prototype.autogeneratePlainText = undefined;

  /**
   * @member {Boolean} autogenerateUTM
   */
  exports.prototype.autogenerateUTM = undefined;

  /**
   * @member {String} excludedSegmentStr
   */
  exports.prototype.excludedSegmentStr = undefined;

  /**
   * @member {String} fromEmail
   */
  exports.prototype.fromEmail = undefined;

  /**
   * @member {String} fromName
   */
  exports.prototype.fromName = undefined;

  /**
   * @member {String} htmlCode
   */
  exports.prototype.htmlCode = undefined;

  /**
   * @member {String} includedSegmentStr
   */
  exports.prototype.includedSegmentStr = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} plainText
   */
  exports.prototype.plainText = undefined;

  /**
   * @member {String} preferredTimeCondition
   */
  exports.prototype.preferredTimeCondition = undefined;

  /**
   * @member {String} preferredTimezone
   */
  exports.prototype.preferredTimezone = undefined;

  /**
   * @member {String} rss
   */
  exports.prototype.rss = undefined;

  /**
   * @member {String} scheduleCondition
   */
  exports.prototype.scheduleCondition = undefined;

  /**
   * @member {Number} scheduleType
   */
  exports.prototype.scheduleType = undefined;

  /**
   * @member {Boolean} sendInContactsTimezone
   */
  exports.prototype.sendInContactsTimezone = undefined;

  /**
   * @member {Boolean} smartSend
   */
  exports.prototype.smartSend = undefined;

  /**
   * @member {Number} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {String} subject
   */
  exports.prototype.subject = undefined;

  /**
   * @member {String} templateCode
   */
  exports.prototype.templateCode = undefined;

  /**
   * @member {String} timeCondition
   */
  exports.prototype.timeCondition = undefined;

  /**
   * @member {String} timezone
   */
  exports.prototype.timezone = undefined;

  /**
   * @member {Boolean} trackReply
   */
  exports.prototype.trackReply = undefined;

  /**
   * @member {Number} type
   */
  exports.prototype.type = undefined;


  return exports;

}));
