/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsAutomationActionDurationType', 'model/ModelsAutomationActionType', 'model/ModelsIntegrationType', 'model/ModelsSelect2ElementWrapper'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsAutomationActionDurationType'), require('./ModelsAutomationActionType'), require('./ModelsIntegrationType'), require('./ModelsSelect2ElementWrapper'));
  } else {
    // Browser globals (root is window)
    if (!root.SendXAppServerV2) {
      root.SendXAppServerV2 = {};
    }
    root.SendXAppServerV2.ModelsAutomationAction = factory(root.SendXAppServerV2.ApiClient, root.SendXAppServerV2.ModelsAutomationActionDurationType, root.SendXAppServerV2.ModelsAutomationActionType, root.SendXAppServerV2.ModelsIntegrationType, root.SendXAppServerV2.ModelsSelect2ElementWrapper);
  }
}(this, function(ApiClient, ModelsAutomationActionDurationType, ModelsAutomationActionType, ModelsIntegrationType, ModelsSelect2ElementWrapper) {
  'use strict';

  /**
   * The ModelsAutomationAction model module.
   * @module model/ModelsAutomationAction
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsAutomationAction</code>.
   * @alias module:model/ModelsAutomationAction
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsAutomationAction</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsAutomationAction} obj Optional instance to populate.
   * @return {module:model/ModelsAutomationAction} The populated <code>ModelsAutomationAction</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('DurationType'))
        obj.durationType = ModelsAutomationActionDurationType.constructFromObject(data['DurationType']);
      if (data.hasOwnProperty('DurationValue'))
        obj.durationValue = ApiClient.convertToType(data['DurationValue'], 'Number');
      if (data.hasOwnProperty('Id'))
        obj.id = ApiClient.convertToType(data['Id'], 'Number');
      if (data.hasOwnProperty('MetaData'))
        obj.metaData = ApiClient.convertToType(data['MetaData'], 'String');
      if (data.hasOwnProperty('MetaDataElementWrapper'))
        obj.metaDataElementWrapper = ModelsSelect2ElementWrapper.constructFromObject(data['MetaDataElementWrapper']);
      if (data.hasOwnProperty('Provider'))
        obj.provider = ModelsIntegrationType.constructFromObject(data['Provider']);
      if (data.hasOwnProperty('Type'))
        obj.type = ModelsAutomationActionType.constructFromObject(data['Type']);
    }
    return obj;
  }

  /**
   * @member {module:model/ModelsAutomationActionDurationType} durationType
   */
  exports.prototype.durationType = undefined;

  /**
   * @member {Number} durationValue
   */
  exports.prototype.durationValue = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} metaData
   */
  exports.prototype.metaData = undefined;

  /**
   * @member {module:model/ModelsSelect2ElementWrapper} metaDataElementWrapper
   */
  exports.prototype.metaDataElementWrapper = undefined;

  /**
   * @member {module:model/ModelsIntegrationType} provider
   */
  exports.prototype.provider = undefined;

  /**
   * @member {module:model/ModelsAutomationActionType} type
   */
  exports.prototype.type = undefined;


  return exports;

}));
