/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsDripStepDurationUnit', 'model/ModelsDripStepStatus', 'model/ModelsSelect2ElementWrapper'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsDripStepDurationUnit'), require('./ModelsDripStepStatus'), require('./ModelsSelect2ElementWrapper'));
  } else {
    // Browser globals (root is window)
    if (!root.SendXAppServerV2) {
      root.SendXAppServerV2 = {};
    }
    root.SendXAppServerV2.ModelsDripStep = factory(root.SendXAppServerV2.ApiClient, root.SendXAppServerV2.ModelsDripStepDurationUnit, root.SendXAppServerV2.ModelsDripStepStatus, root.SendXAppServerV2.ModelsSelect2ElementWrapper);
  }
}(this, function(ApiClient, ModelsDripStepDurationUnit, ModelsDripStepStatus, ModelsSelect2ElementWrapper) {
  'use strict';

  /**
   * The ModelsDripStep model module.
   * @module model/ModelsDripStep
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsDripStep</code>.
   * @alias module:model/ModelsDripStep
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsDripStep</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsDripStep} obj Optional instance to populate.
   * @return {module:model/ModelsDripStep} The populated <code>ModelsDripStep</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('autogeneratePlainText'))
        obj.autogeneratePlainText = ApiClient.convertToType(data['autogeneratePlainText'], 'Boolean');
      if (data.hasOwnProperty('duration'))
        obj.duration = ApiClient.convertToType(data['duration'], 'Number');
      if (data.hasOwnProperty('durationUnit'))
        obj.durationUnit = ModelsDripStepDurationUnit.constructFromObject(data['durationUnit']);
      if (data.hasOwnProperty('encryptedId'))
        obj.encryptedId = ApiClient.convertToType(data['encryptedId'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('metadata'))
        obj.metadata = ApiClient.convertToType(data['metadata'], 'String');
      if (data.hasOwnProperty('order'))
        obj.order = ApiClient.convertToType(data['order'], 'Number');
      if (data.hasOwnProperty('segmentOptions'))
        obj.segmentOptions = ApiClient.convertToType(data['segmentOptions'], [ModelsSelect2ElementWrapper]);
      if (data.hasOwnProperty('status'))
        obj.status = ModelsDripStepStatus.constructFromObject(data['status']);
    }
    return obj;
  }

  /**
   * @member {Boolean} autogeneratePlainText
   */
  exports.prototype.autogeneratePlainText = undefined;

  /**
   * @member {Number} duration
   */
  exports.prototype.duration = undefined;

  /**
   * @member {module:model/ModelsDripStepDurationUnit} durationUnit
   */
  exports.prototype.durationUnit = undefined;

  /**
   * @member {String} encryptedId
   */
  exports.prototype.encryptedId = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} metadata
   */
  exports.prototype.metadata = undefined;

  /**
   * @member {Number} order
   */
  exports.prototype.order = undefined;

  /**
   * @member {Array.<module:model/ModelsSelect2ElementWrapper>} segmentOptions
   */
  exports.prototype.segmentOptions = undefined;

  /**
   * @member {module:model/ModelsDripStepStatus} status
   */
  exports.prototype.status = undefined;


  return exports;

}));
