/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsTeamType'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ModelsTeamType'));
  } else {
    // Browser globals (root is window)
    if (!root.SendXAppServerV2) {
      root.SendXAppServerV2 = {};
    }
    root.SendXAppServerV2.ModelsTeam = factory(root.SendXAppServerV2.ApiClient, root.SendXAppServerV2.ModelsTeamType);
  }
}(this, function(ApiClient, ModelsTeamType) {
  'use strict';

  /**
   * The ModelsTeam model module.
   * @module model/ModelsTeam
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ModelsTeam</code>.
   * @alias module:model/ModelsTeam
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ModelsTeam</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelsTeam} obj Optional instance to populate.
   * @return {module:model/ModelsTeam} The populated <code>ModelsTeam</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('Address'))
        obj.address = ApiClient.convertToType(data['Address'], 'String');
      if (data.hasOwnProperty('CompanyName'))
        obj.companyName = ApiClient.convertToType(data['CompanyName'], 'String');
      if (data.hasOwnProperty('Created'))
        obj.created = ApiClient.convertToType(data['Created'], 'String');
      if (data.hasOwnProperty('CustomProviderId'))
        obj.customProviderId = ApiClient.convertToType(data['CustomProviderId'], 'Number');
      if (data.hasOwnProperty('CustomTestProviderId'))
        obj.customTestProviderId = ApiClient.convertToType(data['CustomTestProviderId'], 'Number');
      if (data.hasOwnProperty('DefaultProviderId'))
        obj.defaultProviderId = ApiClient.convertToType(data['DefaultProviderId'], 'Number');
      if (data.hasOwnProperty('DefaultTestProviderId'))
        obj.defaultTestProviderId = ApiClient.convertToType(data['DefaultTestProviderId'], 'Number');
      if (data.hasOwnProperty('ProviderType'))
        obj.providerType = ApiClient.convertToType(data['ProviderType'], 'Number');
      if (data.hasOwnProperty('Updated'))
        obj.updated = ApiClient.convertToType(data['Updated'], 'String');
      if (data.hasOwnProperty('apiKey'))
        obj.apiKey = ApiClient.convertToType(data['apiKey'], 'String');
      if (data.hasOwnProperty('currency_format'))
        obj.currencyFormat = ApiClient.convertToType(data['currency_format'], 'String');
      if (data.hasOwnProperty('default_currency'))
        obj.defaultCurrency = ApiClient.convertToType(data['default_currency'], 'String');
      if (data.hasOwnProperty('default_email'))
        obj.defaultEmail = ApiClient.convertToType(data['default_email'], 'String');
      if (data.hasOwnProperty('default_from_name'))
        obj.defaultFromName = ApiClient.convertToType(data['default_from_name'], 'String');
      if (data.hasOwnProperty('default_reply_to_email'))
        obj.defaultReplyToEmail = ApiClient.convertToType(data['default_reply_to_email'], 'String');
      if (data.hasOwnProperty('delay_between_emails'))
        obj.delayBetweenEmails = ApiClient.convertToType(data['delay_between_emails'], 'Number');
      if (data.hasOwnProperty('enable_auto_page_track'))
        obj.enableAutoPageTrack = ApiClient.convertToType(data['enable_auto_page_track'], 'Boolean');
      if (data.hasOwnProperty('encrypted_id'))
        obj.encryptedId = ApiClient.convertToType(data['encrypted_id'], 'String');
      if (data.hasOwnProperty('global_unsubscribe_success_page'))
        obj.globalUnsubscribeSuccessPage = ApiClient.convertToType(data['global_unsubscribe_success_page'], 'String');
      if (data.hasOwnProperty('global_unsubscribe_text'))
        obj.globalUnsubscribeText = ApiClient.convertToType(data['global_unsubscribe_text'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('is_contact_added_via_form'))
        obj.isContactAddedViaForm = ApiClient.convertToType(data['is_contact_added_via_form'], 'Boolean');
      if (data.hasOwnProperty('is_contact_added_via_landingpage'))
        obj.isContactAddedViaLandingpage = ApiClient.convertToType(data['is_contact_added_via_landingpage'], 'Boolean');
      if (data.hasOwnProperty('is_contact_added_via_popup'))
        obj.isContactAddedViaPopup = ApiClient.convertToType(data['is_contact_added_via_popup'], 'Boolean');
      if (data.hasOwnProperty('is_global_unsubscribe_only'))
        obj.isGlobalUnsubscribeOnly = ApiClient.convertToType(data['is_global_unsubscribe_only'], 'Boolean');
      if (data.hasOwnProperty('is_impression_via_form'))
        obj.isImpressionViaForm = ApiClient.convertToType(data['is_impression_via_form'], 'Boolean');
      if (data.hasOwnProperty('is_impression_via_landingpage'))
        obj.isImpressionViaLandingpage = ApiClient.convertToType(data['is_impression_via_landingpage'], 'Boolean');
      if (data.hasOwnProperty('is_impression_via_popup'))
        obj.isImpressionViaPopup = ApiClient.convertToType(data['is_impression_via_popup'], 'Boolean');
      if (data.hasOwnProperty('isBulkSender'))
        obj.isBulkSender = ApiClient.convertToType(data['isBulkSender'], 'Boolean');
      if (data.hasOwnProperty('landing_page_custom_domain'))
        obj.landingPageCustomDomain = ApiClient.convertToType(data['landing_page_custom_domain'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('sendpost_subaccount_api_key'))
        obj.sendpostSubaccountApiKey = ApiClient.convertToType(data['sendpost_subaccount_api_key'], 'String');
      if (data.hasOwnProperty('sendpost_subaccount_id'))
        obj.sendpostSubaccountId = ApiClient.convertToType(data['sendpost_subaccount_id'], 'Number');
      if (data.hasOwnProperty('type'))
        obj.type = ModelsTeamType.constructFromObject(data['type']);
    }
    return obj;
  }

  /**
   * @member {String} address
   */
  exports.prototype.address = undefined;

  /**
   * @member {String} companyName
   */
  exports.prototype.companyName = undefined;

  /**
   * @member {String} created
   */
  exports.prototype.created = undefined;

  /**
   * @member {Number} customProviderId
   */
  exports.prototype.customProviderId = undefined;

  /**
   * @member {Number} customTestProviderId
   */
  exports.prototype.customTestProviderId = undefined;

  /**
   * @member {Number} defaultProviderId
   */
  exports.prototype.defaultProviderId = undefined;

  /**
   * @member {Number} defaultTestProviderId
   */
  exports.prototype.defaultTestProviderId = undefined;

  /**
   * @member {Number} providerType
   */
  exports.prototype.providerType = undefined;

  /**
   * @member {String} updated
   */
  exports.prototype.updated = undefined;

  /**
   * @member {String} apiKey
   */
  exports.prototype.apiKey = undefined;

  /**
   * @member {String} currencyFormat
   */
  exports.prototype.currencyFormat = undefined;

  /**
   * @member {String} defaultCurrency
   */
  exports.prototype.defaultCurrency = undefined;

  /**
   * @member {String} defaultEmail
   */
  exports.prototype.defaultEmail = undefined;

  /**
   * @member {String} defaultFromName
   */
  exports.prototype.defaultFromName = undefined;

  /**
   * @member {String} defaultReplyToEmail
   */
  exports.prototype.defaultReplyToEmail = undefined;

  /**
   * @member {Number} delayBetweenEmails
   */
  exports.prototype.delayBetweenEmails = undefined;

  /**
   * @member {Boolean} enableAutoPageTrack
   */
  exports.prototype.enableAutoPageTrack = undefined;

  /**
   * @member {String} encryptedId
   */
  exports.prototype.encryptedId = undefined;

  /**
   * @member {String} globalUnsubscribeSuccessPage
   */
  exports.prototype.globalUnsubscribeSuccessPage = undefined;

  /**
   * @member {String} globalUnsubscribeText
   */
  exports.prototype.globalUnsubscribeText = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {Boolean} isContactAddedViaForm
   */
  exports.prototype.isContactAddedViaForm = undefined;

  /**
   * @member {Boolean} isContactAddedViaLandingpage
   */
  exports.prototype.isContactAddedViaLandingpage = undefined;

  /**
   * @member {Boolean} isContactAddedViaPopup
   */
  exports.prototype.isContactAddedViaPopup = undefined;

  /**
   * @member {Boolean} isGlobalUnsubscribeOnly
   */
  exports.prototype.isGlobalUnsubscribeOnly = undefined;

  /**
   * @member {Boolean} isImpressionViaForm
   */
  exports.prototype.isImpressionViaForm = undefined;

  /**
   * @member {Boolean} isImpressionViaLandingpage
   */
  exports.prototype.isImpressionViaLandingpage = undefined;

  /**
   * @member {Boolean} isImpressionViaPopup
   */
  exports.prototype.isImpressionViaPopup = undefined;

  /**
   * @member {Boolean} isBulkSender
   */
  exports.prototype.isBulkSender = undefined;

  /**
   * @member {String} landingPageCustomDomain
   */
  exports.prototype.landingPageCustomDomain = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} sendpostSubaccountApiKey
   */
  exports.prototype.sendpostSubaccountApiKey = undefined;

  /**
   * @member {Number} sendpostSubaccountId
   */
  exports.prototype.sendpostSubaccountId = undefined;

  /**
   * @member {module:model/ModelsTeamType} type
   */
  exports.prototype.type = undefined;


  return exports;

}));
