/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsDeleteResponse', 'model/ModelsTag'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ModelsDeleteResponse'), require('../model/ModelsTag'));
  } else {
    // Browser globals (root is window)
    if (!root.SendXAppServerV2) {
      root.SendXAppServerV2 = {};
    }
    root.SendXAppServerV2.TeamstagApi = factory(root.SendXAppServerV2.ApiClient, root.SendXAppServerV2.ModelsDeleteResponse, root.SendXAppServerV2.ModelsTag);
  }
}(this, function(ApiClient, ModelsDeleteResponse, ModelsTag) {
  'use strict';

  /**
   * Teamstag service.
   * @module api/TeamstagApi
   * @version 1.0.0
   */

  /**
   * Constructs a new TeamstagApi. 
   * @alias module:api/TeamstagApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the teamTagRouterCreate operation.
     * @callback module:api/TeamstagApi~teamTagRouterCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsTag} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Tag
     * @param {String} xTeamApiKey Account API Key
     * @param {module:model/ModelsTag} body The Tag content
     * @param {module:api/TeamstagApi~teamTagRouterCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsTag}
     */
    this.teamTagRouterCreate = function(xTeamApiKey, body, callback) {
      var postBody = body;

      // verify the required parameter 'xTeamApiKey' is set
      if (xTeamApiKey === undefined || xTeamApiKey === null) {
        throw new Error("Missing the required parameter 'xTeamApiKey' when calling teamTagRouterCreate");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling teamTagRouterCreate");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Team-ApiKey': xTeamApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ModelsTag;

      return this.apiClient.callApi(
        '/teams/tag/', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the teamTagRouterDeleteTag operation.
     * @callback module:api/TeamstagApi~teamTagRouterDeleteTagCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsDeleteResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes Tag
     * @param {String} xTeamApiKey Team API Key
     * @param {Number} tagId The TagId you want to delete
     * @param {module:api/TeamstagApi~teamTagRouterDeleteTagCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsDeleteResponse}
     */
    this.teamTagRouterDeleteTag = function(xTeamApiKey, tagId, callback) {
      var postBody = null;

      // verify the required parameter 'xTeamApiKey' is set
      if (xTeamApiKey === undefined || xTeamApiKey === null) {
        throw new Error("Missing the required parameter 'xTeamApiKey' when calling teamTagRouterDeleteTag");
      }

      // verify the required parameter 'tagId' is set
      if (tagId === undefined || tagId === null) {
        throw new Error("Missing the required parameter 'tagId' when calling teamTagRouterDeleteTag");
      }


      var pathParams = {
        'tagId': tagId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Team-ApiKey': xTeamApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ModelsDeleteResponse;

      return this.apiClient.callApi(
        '/teams/tag/{tagId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the teamTagRouterGetAllTags operation.
     * @callback module:api/TeamstagApi~teamTagRouterGetAllTagsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ModelsTag>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All AllTags
     * @param {String} xTeamApiKey Team API Key
     * @param {Object} opts Optional parameters
     * @param {Number} opts.offset offset
     * @param {Number} opts.limit limit
     * @param {String} opts.search search
     * @param {module:api/TeamstagApi~teamTagRouterGetAllTagsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ModelsTag>}
     */
    this.teamTagRouterGetAllTags = function(xTeamApiKey, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'xTeamApiKey' is set
      if (xTeamApiKey === undefined || xTeamApiKey === null) {
        throw new Error("Missing the required parameter 'xTeamApiKey' when calling teamTagRouterGetAllTags");
      }


      var pathParams = {
      };
      var queryParams = {
        'offset': opts['offset'],
        'limit': opts['limit'],
        'search': opts['search'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Team-ApiKey': xTeamApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [ModelsTag];

      return this.apiClient.callApi(
        '/teams/tag/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the teamTagRouterGetTag operation.
     * @callback module:api/TeamstagApi~teamTagRouterGetTagCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsTag} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * GetTag Tag
     * @param {String} xTeamApiKey Team API Key
     * @param {Number} tagId The TagId you want to delete
     * @param {module:api/TeamstagApi~teamTagRouterGetTagCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsTag}
     */
    this.teamTagRouterGetTag = function(xTeamApiKey, tagId, callback) {
      var postBody = null;

      // verify the required parameter 'xTeamApiKey' is set
      if (xTeamApiKey === undefined || xTeamApiKey === null) {
        throw new Error("Missing the required parameter 'xTeamApiKey' when calling teamTagRouterGetTag");
      }

      // verify the required parameter 'tagId' is set
      if (tagId === undefined || tagId === null) {
        throw new Error("Missing the required parameter 'tagId' when calling teamTagRouterGetTag");
      }


      var pathParams = {
        'tagId': tagId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Team-ApiKey': xTeamApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ModelsTag;

      return this.apiClient.callApi(
        '/teams/tag/{tagId}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the teamTagRouterUpdateTag operation.
     * @callback module:api/TeamstagApi~teamTagRouterUpdateTagCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsTag} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * UpdateTag Tag
     * @param {String} xTeamApiKey Team API Key
     * @param {Number} tagId The TagId you want to delete
     * @param {module:api/TeamstagApi~teamTagRouterUpdateTagCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsTag}
     */
    this.teamTagRouterUpdateTag = function(xTeamApiKey, tagId, callback) {
      var postBody = null;

      // verify the required parameter 'xTeamApiKey' is set
      if (xTeamApiKey === undefined || xTeamApiKey === null) {
        throw new Error("Missing the required parameter 'xTeamApiKey' when calling teamTagRouterUpdateTag");
      }

      // verify the required parameter 'tagId' is set
      if (tagId === undefined || tagId === null) {
        throw new Error("Missing the required parameter 'tagId' when calling teamTagRouterUpdateTag");
      }


      var pathParams = {
        'tagId': tagId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Team-ApiKey': xTeamApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ModelsTag;

      return this.apiClient.callApi(
        '/teams/tag/{tagId}', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
