/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ModelsDeleteResponse', 'model/ModelsList', 'model/ModelsListDeleteRequest', 'model/ModelsTag'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ModelsDeleteResponse'), require('../model/ModelsList'), require('../model/ModelsListDeleteRequest'), require('../model/ModelsTag'));
  } else {
    // Browser globals (root is window)
    if (!root.SendXAppServerV2) {
      root.SendXAppServerV2 = {};
    }
    root.SendXAppServerV2.TeamslistApi = factory(root.SendXAppServerV2.ApiClient, root.SendXAppServerV2.ModelsDeleteResponse, root.SendXAppServerV2.ModelsList, root.SendXAppServerV2.ModelsListDeleteRequest, root.SendXAppServerV2.ModelsTag);
  }
}(this, function(ApiClient, ModelsDeleteResponse, ModelsList, ModelsListDeleteRequest, ModelsTag) {
  'use strict';

  /**
   * Teamslist service.
   * @module api/TeamslistApi
   * @version 1.0.0
   */

  /**
   * Constructs a new TeamslistApi. 
   * @alias module:api/TeamslistApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the teamListRouterCreate operation.
     * @callback module:api/TeamslistApi~teamListRouterCreateCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsList} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create List
     * @param {String} xTeamApiKey Account API Key
     * @param {module:model/ModelsTag} body The Tag content
     * @param {module:api/TeamslistApi~teamListRouterCreateCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsList}
     */
    this.teamListRouterCreate = function(xTeamApiKey, body, callback) {
      var postBody = body;

      // verify the required parameter 'xTeamApiKey' is set
      if (xTeamApiKey === undefined || xTeamApiKey === null) {
        throw new Error("Missing the required parameter 'xTeamApiKey' when calling teamListRouterCreate");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling teamListRouterCreate");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Team-ApiKey': xTeamApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ModelsList;

      return this.apiClient.callApi(
        '/teams/list/', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the teamListRouterDeleteList operation.
     * @callback module:api/TeamslistApi~teamListRouterDeleteListCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelsDeleteResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Deletes List
     * @param {String} xTeamApiKey Team API Key
     * @param {Number} listId The TagId you want to delete
     * @param {module:model/ModelsListDeleteRequest} body The list deletion content
     * @param {module:api/TeamslistApi~teamListRouterDeleteListCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ModelsDeleteResponse}
     */
    this.teamListRouterDeleteList = function(xTeamApiKey, listId, body, callback) {
      var postBody = body;

      // verify the required parameter 'xTeamApiKey' is set
      if (xTeamApiKey === undefined || xTeamApiKey === null) {
        throw new Error("Missing the required parameter 'xTeamApiKey' when calling teamListRouterDeleteList");
      }

      // verify the required parameter 'listId' is set
      if (listId === undefined || listId === null) {
        throw new Error("Missing the required parameter 'listId' when calling teamListRouterDeleteList");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling teamListRouterDeleteList");
      }


      var pathParams = {
        'listId': listId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Team-ApiKey': xTeamApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = ModelsDeleteResponse;

      return this.apiClient.callApi(
        '/teams/list/{listId}', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the teamListRouterGetAllLists operation.
     * @callback module:api/TeamslistApi~teamListRouterGetAllListsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ModelsList>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All All Lists
     * @param {String} xTeamApiKey Team API Key
     * @param {Object} opts Optional parameters
     * @param {Number} opts.offset offset
     * @param {Number} opts.limit limit
     * @param {String} opts.search search
     * @param {module:api/TeamslistApi~teamListRouterGetAllListsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ModelsList>}
     */
    this.teamListRouterGetAllLists = function(xTeamApiKey, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'xTeamApiKey' is set
      if (xTeamApiKey === undefined || xTeamApiKey === null) {
        throw new Error("Missing the required parameter 'xTeamApiKey' when calling teamListRouterGetAllLists");
      }


      var pathParams = {
      };
      var queryParams = {
        'offset': opts['offset'],
        'limit': opts['limit'],
        'search': opts['search'],
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'X-Team-ApiKey': xTeamApiKey
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [ModelsList];

      return this.apiClient.callApi(
        '/teams/list/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
