/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SendXAppServerV2);
  }
}(this, function(expect, SendXAppServerV2) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ModelsAutomationAction', function() {
      beforeEach(function() {
        instance = new SendXAppServerV2.ModelsAutomationAction();
      });

      it('should create an instance of ModelsAutomationAction', function() {
        // TODO: update the code to test ModelsAutomationAction
        expect(instance).to.be.a(SendXAppServerV2.ModelsAutomationAction);
      });

      it('should have the property durationType (base name: "DurationType")', function() {
        // TODO: update the code to test the property durationType
        expect(instance).to.have.property('durationType');
        // expect(instance.durationType).to.be(expectedValueLiteral);
      });

      it('should have the property durationValue (base name: "DurationValue")', function() {
        // TODO: update the code to test the property durationValue
        expect(instance).to.have.property('durationValue');
        // expect(instance.durationValue).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "Id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property metaData (base name: "MetaData")', function() {
        // TODO: update the code to test the property metaData
        expect(instance).to.have.property('metaData');
        // expect(instance.metaData).to.be(expectedValueLiteral);
      });

      it('should have the property metaDataElementWrapper (base name: "MetaDataElementWrapper")', function() {
        // TODO: update the code to test the property metaDataElementWrapper
        expect(instance).to.have.property('metaDataElementWrapper');
        // expect(instance.metaDataElementWrapper).to.be(expectedValueLiteral);
      });

      it('should have the property provider (base name: "Provider")', function() {
        // TODO: update the code to test the property provider
        expect(instance).to.have.property('provider');
        // expect(instance.provider).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "Type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

    });
  });

}));
