/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SendXAppServerV2);
  }
}(this, function(expect, SendXAppServerV2) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ModelsBulkRequest', function() {
      beforeEach(function() {
        instance = new SendXAppServerV2.ModelsBulkRequest();
      });

      it('should create an instance of ModelsBulkRequest', function() {
        // TODO: update the code to test ModelsBulkRequest
        expect(instance).to.be.a(SendXAppServerV2.ModelsBulkRequest);
      });

      it('should have the property bulkAction (base name: "bulkAction")', function() {
        // TODO: update the code to test the property bulkAction
        expect(instance).to.have.property('bulkAction');
        // expect(instance.bulkAction).to.be(expectedValueLiteral);
      });

      it('should have the property bulkTrigger (base name: "bulkTrigger")', function() {
        // TODO: update the code to test the property bulkTrigger
        expect(instance).to.have.property('bulkTrigger');
        // expect(instance.bulkTrigger).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

    });
  });

}));
