/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SendXAppServerV2);
  }
}(this, function(expect, SendXAppServerV2) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ModelsABTestRequest', function() {
      beforeEach(function() {
        instance = new SendXAppServerV2.ModelsABTestRequest();
      });

      it('should create an instance of ModelsABTestRequest', function() {
        // TODO: update the code to test ModelsABTestRequest
        expect(instance).to.be.a(SendXAppServerV2.ModelsABTestRequest);
      });

      it('should have the property autogeneratePlainText (base name: "AutogeneratePlainText")', function() {
        // TODO: update the code to test the property autogeneratePlainText
        expect(instance).to.have.property('autogeneratePlainText');
        // expect(instance.autogeneratePlainText).to.be(expectedValueLiteral);
      });

      it('should have the property autogenerateUTM (base name: "AutogenerateUTM")', function() {
        // TODO: update the code to test the property autogenerateUTM
        expect(instance).to.have.property('autogenerateUTM');
        // expect(instance.autogenerateUTM).to.be(expectedValueLiteral);
      });

      it('should have the property sendInContactsTimezone (base name: "SendInContactsTimezone")', function() {
        // TODO: update the code to test the property sendInContactsTimezone
        expect(instance).to.have.property('sendInContactsTimezone');
        // expect(instance.sendInContactsTimezone).to.be(expectedValueLiteral);
      });

      it('should have the property smartSend (base name: "SmartSend")', function() {
        // TODO: update the code to test the property smartSend
        expect(instance).to.have.property('smartSend');
        // expect(instance.smartSend).to.be(expectedValueLiteral);
      });

      it('should have the property trackReply (base name: "TrackReply")', function() {
        // TODO: update the code to test the property trackReply
        expect(instance).to.have.property('trackReply');
        // expect(instance.trackReply).to.be(expectedValueLiteral);
      });

      it('should have the property variationsStr (base name: "VariationsStr")', function() {
        // TODO: update the code to test the property variationsStr
        expect(instance).to.have.property('variationsStr');
        // expect(instance.variationsStr).to.be(expectedValueLiteral);
      });

      it('should have the property excludedSegmentStr (base name: "excludedSegmentStr")', function() {
        // TODO: update the code to test the property excludedSegmentStr
        expect(instance).to.have.property('excludedSegmentStr');
        // expect(instance.excludedSegmentStr).to.be(expectedValueLiteral);
      });

      it('should have the property fromEmail (base name: "fromEmail")', function() {
        // TODO: update the code to test the property fromEmail
        expect(instance).to.have.property('fromEmail');
        // expect(instance.fromEmail).to.be(expectedValueLiteral);
      });

      it('should have the property fromName (base name: "fromName")', function() {
        // TODO: update the code to test the property fromName
        expect(instance).to.have.property('fromName');
        // expect(instance.fromName).to.be(expectedValueLiteral);
      });

      it('should have the property htmlCode (base name: "htmlCode")', function() {
        // TODO: update the code to test the property htmlCode
        expect(instance).to.have.property('htmlCode');
        // expect(instance.htmlCode).to.be(expectedValueLiteral);
      });

      it('should have the property includedSegmentStr (base name: "includedSegmentStr")', function() {
        // TODO: update the code to test the property includedSegmentStr
        expect(instance).to.have.property('includedSegmentStr');
        // expect(instance.includedSegmentStr).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property plainText (base name: "plainText")', function() {
        // TODO: update the code to test the property plainText
        expect(instance).to.have.property('plainText');
        // expect(instance.plainText).to.be(expectedValueLiteral);
      });

      it('should have the property scheduleCondition (base name: "scheduleCondition")', function() {
        // TODO: update the code to test the property scheduleCondition
        expect(instance).to.have.property('scheduleCondition');
        // expect(instance.scheduleCondition).to.be(expectedValueLiteral);
      });

      it('should have the property scheduleType (base name: "scheduleType")', function() {
        // TODO: update the code to test the property scheduleType
        expect(instance).to.have.property('scheduleType');
        // expect(instance.scheduleType).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property subject (base name: "subject")', function() {
        // TODO: update the code to test the property subject
        expect(instance).to.have.property('subject');
        // expect(instance.subject).to.be(expectedValueLiteral);
      });

      it('should have the property templateCode (base name: "templateCode")', function() {
        // TODO: update the code to test the property templateCode
        expect(instance).to.have.property('templateCode');
        // expect(instance.templateCode).to.be(expectedValueLiteral);
      });

      it('should have the property testParameter (base name: "testParameter")', function() {
        // TODO: update the code to test the property testParameter
        expect(instance).to.have.property('testParameter');
        // expect(instance.testParameter).to.be(expectedValueLiteral);
      });

      it('should have the property testPercent (base name: "testPercent")', function() {
        // TODO: update the code to test the property testPercent
        expect(instance).to.have.property('testPercent');
        // expect(instance.testPercent).to.be(expectedValueLiteral);
      });

      it('should have the property timeCondition (base name: "timeCondition")', function() {
        // TODO: update the code to test the property timeCondition
        expect(instance).to.have.property('timeCondition');
        // expect(instance.timeCondition).to.be(expectedValueLiteral);
      });

      it('should have the property timeZone (base name: "timeZone")', function() {
        // TODO: update the code to test the property timeZone
        expect(instance).to.have.property('timeZone');
        // expect(instance.timeZone).to.be(expectedValueLiteral);
      });

      it('should have the property waitDurationType (base name: "waitDurationType")', function() {
        // TODO: update the code to test the property waitDurationType
        expect(instance).to.have.property('waitDurationType');
        // expect(instance.waitDurationType).to.be(expectedValueLiteral);
      });

      it('should have the property waitDurationValue (base name: "waitDurationValue")', function() {
        // TODO: update the code to test the property waitDurationValue
        expect(instance).to.have.property('waitDurationValue');
        // expect(instance.waitDurationValue).to.be(expectedValueLiteral);
      });

    });
  });

}));
