/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SendXAppServerV2);
  }
}(this, function(expect, SendXAppServerV2) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ModelsDrip', function() {
      beforeEach(function() {
        instance = new SendXAppServerV2.ModelsDrip();
      });

      it('should create an instance of ModelsDrip', function() {
        // TODO: update the code to test ModelsDrip
        expect(instance).to.be.a(SendXAppServerV2.ModelsDrip);
      });

      it('should have the property autogenerateUTM (base name: "autogenerateUTM")', function() {
        // TODO: update the code to test the property autogenerateUTM
        expect(instance).to.have.property('autogenerateUTM');
        // expect(instance.autogenerateUTM).to.be(expectedValueLiteral);
      });

      it('should have the property channel (base name: "channel")', function() {
        // TODO: update the code to test the property channel
        expect(instance).to.have.property('channel');
        // expect(instance.channel).to.be(expectedValueLiteral);
      });

      it('should have the property encryptedId (base name: "encryptedId")', function() {
        // TODO: update the code to test the property encryptedId
        expect(instance).to.have.property('encryptedId');
        // expect(instance.encryptedId).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property sendInContactsTimezone (base name: "sendInContactsTimezone")', function() {
        // TODO: update the code to test the property sendInContactsTimezone
        expect(instance).to.have.property('sendInContactsTimezone');
        // expect(instance.sendInContactsTimezone).to.be(expectedValueLiteral);
      });

      it('should have the property skipWeekends (base name: "skipWeekends")', function() {
        // TODO: update the code to test the property skipWeekends
        expect(instance).to.have.property('skipWeekends');
        // expect(instance.skipWeekends).to.be(expectedValueLiteral);
      });

      it('should have the property smartSend (base name: "smartSend")', function() {
        // TODO: update the code to test the property smartSend
        expect(instance).to.have.property('smartSend');
        // expect(instance.smartSend).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property strategy (base name: "strategy")', function() {
        // TODO: update the code to test the property strategy
        expect(instance).to.have.property('strategy');
        // expect(instance.strategy).to.be(expectedValueLiteral);
      });

      it('should have the property timeCondition (base name: "time_condition")', function() {
        // TODO: update the code to test the property timeCondition
        expect(instance).to.have.property('timeCondition');
        // expect(instance.timeCondition).to.be(expectedValueLiteral);
      });

      it('should have the property timezone (base name: "timezone")', function() {
        // TODO: update the code to test the property timezone
        expect(instance).to.have.property('timezone');
        // expect(instance.timezone).to.be(expectedValueLiteral);
      });

      it('should have the property trackReply (base name: "trackReply")', function() {
        // TODO: update the code to test the property trackReply
        expect(instance).to.have.property('trackReply');
        // expect(instance.trackReply).to.be(expectedValueLiteral);
      });

    });
  });

}));
