/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SendXAppServerV2);
  }
}(this, function(expect, SendXAppServerV2) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ModelsListDeleteRequest', function() {
      beforeEach(function() {
        instance = new SendXAppServerV2.ModelsListDeleteRequest();
      });

      it('should create an instance of ModelsListDeleteRequest', function() {
        // TODO: update the code to test ModelsListDeleteRequest
        expect(instance).to.be.a(SendXAppServerV2.ModelsListDeleteRequest);
      });

      it('should have the property deleteContacts (base name: "deleteContacts")', function() {
        // TODO: update the code to test the property deleteContacts
        expect(instance).to.have.property('deleteContacts');
        // expect(instance.deleteContacts).to.be(expectedValueLiteral);
      });

    });
  });

}));
