/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SendXAppServerV2);
  }
}(this, function(expect, SendXAppServerV2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SendXAppServerV2.TeamslistApi();
  });

  describe('(package)', function() {
    describe('TeamslistApi', function() {
      describe('teamListRouterCreate', function() {
        it('should call teamListRouterCreate successfully', function(done) {
          // TODO: uncomment, update parameter values for teamListRouterCreate call and complete the assertions
          /*
          var xTeamApiKey = "xTeamApiKey_example";
          var body = new SendXAppServerV2.ModelsTag();
          body.id = "0";
          body.name = "";

          instance.teamListRouterCreate(xTeamApiKey, body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SendXAppServerV2.ModelsList);
            expect(data.confirmFromEmail).to.be.a('string');
            expect(data.confirmFromEmail).to.be("");
            expect(data.confirmFromName).to.be.a('string');
            expect(data.confirmFromName).to.be("");
            expect(data.confirmMailMessage).to.be.a('string');
            expect(data.confirmMailMessage).to.be("");
            expect(data.confirmMailSubject).to.be.a('string');
            expect(data.confirmMailSubject).to.be("");
            expect(data.confirmSuccessPage).to.be.a('string');
            expect(data.confirmSuccessPage).to.be("");
            expect(data.encrypted).to.be.a('string');
            expect(data.encrypted).to.be("");
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            expect(data.sendThankYouMail).to.be.a('boolean');
            expect(data.sendThankYouMail).to.be(false);
            expect(data.thankYouFromEmail).to.be.a('string');
            expect(data.thankYouFromEmail).to.be("");
            expect(data.thankYouFromName).to.be.a('string');
            expect(data.thankYouFromName).to.be("");
            expect(data.thankYouMailMessage).to.be.a('string');
            expect(data.thankYouMailMessage).to.be("");
            expect(data.thankYouMailSubject).to.be.a('string');
            expect(data.thankYouMailSubject).to.be("");
            expect(data.type).to.be.a(SendXAppServerV2.ModelsListType);
    
            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('teamListRouterDeleteList', function() {
        it('should call teamListRouterDeleteList successfully', function(done) {
          // TODO: uncomment, update parameter values for teamListRouterDeleteList call and complete the assertions
          /*
          var xTeamApiKey = "xTeamApiKey_example";
          var listId = 789;
          var body = new SendXAppServerV2.ModelsListDeleteRequest();
          body.deleteContacts = false;

          instance.teamListRouterDeleteList(xTeamApiKey, listId, body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SendXAppServerV2.ModelsDeleteResponse);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.message).to.be.a('string');
            expect(data.message).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('teamListRouterGetAllLists', function() {
        it('should call teamListRouterGetAllLists successfully', function(done) {
          // TODO: uncomment, update parameter values for teamListRouterGetAllLists call and complete the assertions
          /*
          var xTeamApiKey = "xTeamApiKey_example";
          var opts = {};
          opts.offset = 789;
          opts.limit = 789;
          opts.search = "search_example";

          instance.teamListRouterGetAllLists(xTeamApiKey, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(SendXAppServerV2.ModelsList);
              expect(data.confirmFromEmail).to.be.a('string');
              expect(data.confirmFromEmail).to.be("");
              expect(data.confirmFromName).to.be.a('string');
              expect(data.confirmFromName).to.be("");
              expect(data.confirmMailMessage).to.be.a('string');
              expect(data.confirmMailMessage).to.be("");
              expect(data.confirmMailSubject).to.be.a('string');
              expect(data.confirmMailSubject).to.be("");
              expect(data.confirmSuccessPage).to.be.a('string');
              expect(data.confirmSuccessPage).to.be("");
              expect(data.encrypted).to.be.a('string');
              expect(data.encrypted).to.be("");
              expect(data.id).to.be.a('number');
              expect(data.id).to.be("0");
              expect(data.name).to.be.a('string');
              expect(data.name).to.be("");
              expect(data.sendThankYouMail).to.be.a('boolean');
              expect(data.sendThankYouMail).to.be(false);
              expect(data.thankYouFromEmail).to.be.a('string');
              expect(data.thankYouFromEmail).to.be("");
              expect(data.thankYouFromName).to.be.a('string');
              expect(data.thankYouFromName).to.be("");
              expect(data.thankYouMailMessage).to.be.a('string');
              expect(data.thankYouMailMessage).to.be("");
              expect(data.thankYouMailSubject).to.be.a('string');
              expect(data.thankYouMailSubject).to.be("");
              expect(data.type).to.be.a(SendXAppServerV2.ModelsListType);
      
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
