/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SendXAppServerV2);
  }
}(this, function(expect, SendXAppServerV2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SendXAppServerV2.TeamssegmentApi();
  });

  describe('(package)', function() {
    describe('TeamssegmentApi', function() {
      describe('teamSegmentRouterCreate', function() {
        it('should call teamSegmentRouterCreate successfully', function(done) {
          // TODO: uncomment, update parameter values for teamSegmentRouterCreate call and complete the assertions
          /*
          var xTeamApiKey = "xTeamApiKey_example";
          var body = new SendXAppServerV2.ModelsSegment();
          body.conditions = "";
          body.id = "0";
          body.name = "";
          body.type = new SendXAppServerV2.ModelsSegmentType();

          instance.teamSegmentRouterCreate(xTeamApiKey, body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SendXAppServerV2.ModelsSegment);
            expect(data.conditions).to.be.a('string');
            expect(data.conditions).to.be("");
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            expect(data.type).to.be.a(SendXAppServerV2.ModelsSegmentType);
    
            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('teamSegmentRouterGetAlSegments', function() {
        it('should call teamSegmentRouterGetAlSegments successfully', function(done) {
          // TODO: uncomment, update parameter values for teamSegmentRouterGetAlSegments call and complete the assertions
          /*
          var xTeamApiKey = "xTeamApiKey_example";
          var opts = {};
          opts.offset = 789;
          opts.limit = 789;
          opts.search = "search_example";

          instance.teamSegmentRouterGetAlSegments(xTeamApiKey, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(SendXAppServerV2.ModelsDeepEmailSegment);
              expect(data.conditions).to.be.a('string');
              expect(data.conditions).to.be("");
              expect(data.id).to.be.a('number');
              expect(data.id).to.be("0");
              expect(data.name).to.be.a('string');
              expect(data.name).to.be("");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('teamSegmentRouterGetsegment', function() {
        it('should call teamSegmentRouterGetsegment successfully', function(done) {
          // TODO: uncomment, update parameter values for teamSegmentRouterGetsegment call and complete the assertions
          /*
          var xTeamApiKey = "xTeamApiKey_example";
          var segmentId = 789;

          instance.teamSegmentRouterGetsegment(xTeamApiKey, segmentId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(SendXAppServerV2.ModelsSegment);
              expect(data.conditions).to.be.a('string');
              expect(data.conditions).to.be("");
              expect(data.id).to.be.a('number');
              expect(data.id).to.be("0");
              expect(data.name).to.be.a('string');
              expect(data.name).to.be("");
              expect(data.type).to.be.a(SendXAppServerV2.ModelsSegmentType);
      
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
