/*
 * SendX APP Server V2
 * Send App Server
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@sendx.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.25
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SendXAppServerV2);
  }
}(this, function(expect, SendXAppServerV2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SendXAppServerV2.TeamsautomationApi();
  });

  describe('(package)', function() {
    describe('TeamsautomationApi', function() {
      describe('teamAutomationRouterCreateAutomation', function() {
        it('should call teamAutomationRouterCreateAutomation successfully', function(done) {
          // TODO: uncomment, update parameter values for teamAutomationRouterCreateAutomation call and complete the assertions
          /*
          var xTeamApiKey = "xTeamApiKey_example";
          var body = new SendXAppServerV2.ModelsAutomationRequest();
          body.automationAction = [new SendXAppServerV2.ModelsAutomationRequestAction()];
          body.automationAction[0].durationType = "0";
          body.automationAction[0].durationValue = "0";
          body.automationAction[0].metaData = "";
          body.automationAction[0].provider = "0";
          body.automationAction[0].type = "0";
          body.automationTrigger = [new SendXAppServerV2.ModelsAutomationRequestTrigger()];
          body.automationTrigger[0].durationValue = "";
          body.automationTrigger[0].metaData = "";
          body.automationTrigger[0].pageSourceType = "0";
          body.automationTrigger[0].provider = "0";
          body.automationTrigger[0].type = "0";
          body.name = "";
          body.status = false;

          instance.teamAutomationRouterCreateAutomation(xTeamApiKey, body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SendXAppServerV2.ModelsAutomation);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            expect(data.status).to.be.a('boolean');
            expect(data.status).to.be(false);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('teamAutomationRouterDeleteAutomation', function() {
        it('should call teamAutomationRouterDeleteAutomation successfully', function(done) {
          // TODO: uncomment, update parameter values for teamAutomationRouterDeleteAutomation call and complete the assertions
          /*
          var xTeamApiKey = "xTeamApiKey_example";
          var automationId = 789;

          instance.teamAutomationRouterDeleteAutomation(xTeamApiKey, automationId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SendXAppServerV2.ModelsDeleteResponse);
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.message).to.be.a('string');
            expect(data.message).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('teamAutomationRouterGetAllAutomations', function() {
        it('should call teamAutomationRouterGetAllAutomations successfully', function(done) {
          // TODO: uncomment, update parameter values for teamAutomationRouterGetAllAutomations call and complete the assertions
          /*
          var xTeamApiKey = "xTeamApiKey_example";
          var opts = {};
          opts.offset = 789;
          opts.limit = 789;
          opts.search = "search_example";

          instance.teamAutomationRouterGetAllAutomations(xTeamApiKey, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(SendXAppServerV2.ModelsDeepTeamAutomation);
              {
                let dataCtr = data.actions;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a(SendXAppServerV2.ModelsAutomationAction);
                  expect(data.durationType).to.be.a(SendXAppServerV2.ModelsAutomationActionDurationType);
                      expect(data.durationValue).to.be.a('number');
                  expect(data.durationValue).to.be("0");
                  expect(data.id).to.be.a('number');
                  expect(data.id).to.be("0");
                  expect(data.metaData).to.be.a('string');
                  expect(data.metaData).to.be("");
                  expect(data.metaDataElementWrapper).to.be.a(SendXAppServerV2.ModelsSelect2ElementWrapper);
                        expect(data.metaDataElementWrapper.id).to.be.a('string');
                    expect(data.metaDataElementWrapper.id).to.be("");
                    expect(data.metaDataElementWrapper.text).to.be.a('string');
                    expect(data.metaDataElementWrapper.text).to.be("");
                  expect(data.provider).to.be.a(SendXAppServerV2.ModelsIntegrationType);
                      expect(data.type).to.be.a(SendXAppServerV2.ModelsAutomationActionType);
          
  
                        }
              }
              expect(data._date).to.be.a('string');
              expect(data._date).to.be("");
              expect(data.id).to.be.a('number');
              expect(data.id).to.be("0");
              expect(data.name).to.be.a('string');
              expect(data.name).to.be("");
              expect(data.status).to.be.a('boolean');
              expect(data.status).to.be(false);
              {
                let dataCtr = data.triggers;
                expect(dataCtr).to.be.an(Array);
                expect(dataCtr).to.not.be.empty();
                for (let p in dataCtr) {
                  let data = dataCtr[p];
                  expect(data).to.be.a(SendXAppServerV2.ModelsAutomationTrigger);
                  expect(data.id).to.be.a('number');
                  expect(data.id).to.be("0");
                  expect(data.metaData).to.be.a('string');
                  expect(data.metaData).to.be("");
                  expect(data.metaDataElementWrapper).to.be.a(SendXAppServerV2.ModelsSelect2ElementWrapper);
                        expect(data.metaDataElementWrapper.id).to.be.a('string');
                    expect(data.metaDataElementWrapper.id).to.be("");
                    expect(data.metaDataElementWrapper.text).to.be.a('string');
                    expect(data.metaDataElementWrapper.text).to.be("");
                  expect(data.pageSourceType).to.be.a(SendXAppServerV2.ModelsAutomationTriggerPageSourceType);
                      expect(data.pageSourceValue).to.be.a('string');
                  expect(data.pageSourceValue).to.be("");
                  expect(data.provider).to.be.a(SendXAppServerV2.ModelsIntegrationType);
                      expect(data.triggerForExisting).to.be.a('boolean');
                  expect(data.triggerForExisting).to.be(false);
                  expect(data.type).to.be.a(SendXAppServerV2.ModelsAutomationTriggerType);
          
  
                        }
              }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('teamAutomationRouterGetAutomation', function() {
        it('should call teamAutomationRouterGetAutomation successfully', function(done) {
          // TODO: uncomment, update parameter values for teamAutomationRouterGetAutomation call and complete the assertions
          /*
          var xTeamApiKey = "xTeamApiKey_example";
          var automationId = 789;

          instance.teamAutomationRouterGetAutomation(xTeamApiKey, automationId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SendXAppServerV2.ModelsDeepTeamAutomation);
            {
              let dataCtr = data.actions;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(SendXAppServerV2.ModelsAutomationAction);
                expect(data.durationType).to.be.a(SendXAppServerV2.ModelsAutomationActionDurationType);
                    expect(data.durationValue).to.be.a('number');
                expect(data.durationValue).to.be("0");
                expect(data.id).to.be.a('number');
                expect(data.id).to.be("0");
                expect(data.metaData).to.be.a('string');
                expect(data.metaData).to.be("");
                expect(data.metaDataElementWrapper).to.be.a(SendXAppServerV2.ModelsSelect2ElementWrapper);
                      expect(data.metaDataElementWrapper.id).to.be.a('string');
                  expect(data.metaDataElementWrapper.id).to.be("");
                  expect(data.metaDataElementWrapper.text).to.be.a('string');
                  expect(data.metaDataElementWrapper.text).to.be("");
                expect(data.provider).to.be.a(SendXAppServerV2.ModelsIntegrationType);
                    expect(data.type).to.be.a(SendXAppServerV2.ModelsAutomationActionType);
        

                      }
            }
            expect(data._date).to.be.a('string');
            expect(data._date).to.be("");
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            expect(data.status).to.be.a('boolean');
            expect(data.status).to.be(false);
            {
              let dataCtr = data.triggers;
              expect(dataCtr).to.be.an(Array);
              expect(dataCtr).to.not.be.empty();
              for (let p in dataCtr) {
                let data = dataCtr[p];
                expect(data).to.be.a(SendXAppServerV2.ModelsAutomationTrigger);
                expect(data.id).to.be.a('number');
                expect(data.id).to.be("0");
                expect(data.metaData).to.be.a('string');
                expect(data.metaData).to.be("");
                expect(data.metaDataElementWrapper).to.be.a(SendXAppServerV2.ModelsSelect2ElementWrapper);
                      expect(data.metaDataElementWrapper.id).to.be.a('string');
                  expect(data.metaDataElementWrapper.id).to.be("");
                  expect(data.metaDataElementWrapper.text).to.be.a('string');
                  expect(data.metaDataElementWrapper.text).to.be("");
                expect(data.pageSourceType).to.be.a(SendXAppServerV2.ModelsAutomationTriggerPageSourceType);
                    expect(data.pageSourceValue).to.be.a('string');
                expect(data.pageSourceValue).to.be("");
                expect(data.provider).to.be.a(SendXAppServerV2.ModelsIntegrationType);
                    expect(data.triggerForExisting).to.be.a('boolean');
                expect(data.triggerForExisting).to.be(false);
                expect(data.type).to.be.a(SendXAppServerV2.ModelsAutomationTriggerType);
        

                      }
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
